# SPDX-License-Identifier: 0BSD
"""Regenerate docs/cli-reference.md from the live argparse CLI definition.

Usage:
    python scripts/generate_cli_reference.py           # write the doc
    python scripts/generate_cli_reference.py --check   # fail if the doc is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from cpe_access_atlas import __version__
from cpe_access_atlas.cli import build_parser

_OUTPUT_PATH = Path(__file__).resolve().parents[1] / "docs" / "cli-reference.md"


def _subparser_choices(parser: argparse.ArgumentParser) -> dict[str, argparse.ArgumentParser]:
    for action in parser._actions:  # argparse exposes no public API for this lookup
        if isinstance(action, argparse._SubParsersAction):
            return dict(action.choices)
    return {}


def render() -> str:
    parser = build_parser()
    lines = [
        "<!-- Generated by scripts/generate_cli_reference.py. Do not edit by hand. -->",
        "# CLI reference",
        "",
        f"Reference for `cpe-atlas` version {__version__}, generated from the",
        "live `argparse` definition so it cannot drift from the actual CLI.",
        "Regenerate after any CLI change with:",
        "",
        "```shell",
        "python scripts/generate_cli_reference.py",
        "```",
        "",
        "## `cpe-atlas`",
        "",
        "```text",
        parser.format_help().rstrip(),
        "```",
        "",
    ]
    for name, subparser in sorted(_subparser_choices(parser).items()):
        lines.append(f"## `cpe-atlas {name}`")
        lines.append("")
        lines.append("```text")
        lines.append(subparser.format_help().rstrip())
        lines.append("```")
        lines.append("")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    check_only = "--check" in (argv if argv is not None else sys.argv[1:])
    rendered = render()
    if check_only:
        current = _OUTPUT_PATH.read_text(encoding="utf-8") if _OUTPUT_PATH.exists() else ""
        if current != rendered:
            print(
                f"{_OUTPUT_PATH} is stale; run "
                "'python scripts/generate_cli_reference.py' and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{_OUTPUT_PATH} is up to date.")
        return 0
    _OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {_OUTPUT_PATH}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
